---
- name: Get container facts
  become: true
  kolla_container_facts:
    name:
      - keystone
      - keystone_ssh
  register: container_facts

- name: Checking free port for Keystone Admin
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ keystone_admin_listen_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['keystone'] is not defined
    - inventory_hostname in groups['keystone']

- name: Checking free port for Keystone Public
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ keystone_public_listen_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['keystone'] is not defined
    - inventory_hostname in groups['keystone']

- name: Checking free port for Keystone SSH
  vars:
    keystone_ssh: "{{ keystone_services['keystone-ssh'] }}"
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ keystone_ssh_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['keystone_ssh'] is not defined
    - keystone_ssh.enabled | bool
    - inventory_hostname in groups['keystone']
