---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ prometheus_services }}"

- name: Copying over config.json files
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
  register: prometheus_config_jsons
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ prometheus_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over prometheus config file
  vars:
    service: "{{ prometheus_services['prometheus-server']}}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/prometheus-server/prometheus.yml"
  register: prometheus_confs
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - "{{ node_custom_config }}/prometheus/{{ inventory_hostname }}/prometheus.yml"
    - "{{ node_custom_config }}/prometheus/prometheus.yml"
    - "{{ role_path }}/templates/prometheus.yml.j2"
  notify:
    - Restart prometheus-server container

- name: Find prometheus alerting rules
  vars:
    service: "{{ prometheus_services['prometheus-server']}}"
  local_action:
    module: find
    path: "{{ node_custom_config }}/prometheus/rules"
    pattern: "*.rules"
  run_once: True
  register: prometheus_custom_alerting_rules
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool

- name: Create config folder for prometheus alerting rules
  vars:
    service: "{{ prometheus_services['prometheus-server']}}"
  file:
    path: "{{ node_config_directory }}/prometheus-server/rules"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool

- name: Copying over prometheus alerting rules
  vars:
    service: "{{ prometheus_services['prometheus-server']}}"
  copy:
    src: "{{ item.path }}"
    dest: "{{ node_config_directory }}/prometheus-server/rules/{{ item.path | basename }}"
  register: prometheus_alerting_rules
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_items: "{{ prometheus_custom_alerting_rules.files }}"
  notify:
    - Restart prometheus-server container

- name: Copying over prometheus alertmanager config file
  vars:
    service: "{{ prometheus_services['prometheus-alertmanager']}}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/prometheus-alertmanager/prometheus-alertmanager.yml"
  register: prometheus_alertmanager_confs
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - "{{ node_custom_config }}/prometheus/{{ inventory_hostname }}/prometheus-alertmanager.yml"
    - "{{ node_custom_config }}/prometheus/prometheus-alertmanager.yml"
    - "{{ role_path }}/templates/prometheus-alertmanager.yml.j2"
  notify:
    - Restart prometheus-alertmanager container

- name: Copying over my.cnf for mysqld_exporter
  vars:
    service: "{{ prometheus_services['prometheus-mysqld-exporter']}}"
  merge_configs:
    sources:
      - "{{ node_custom_config }}/prometheus-mysqld-exporter/{{ inventory_hostname }}/my.cnf"
      - "{{ node_custom_config }}/prometheus-mysqld-exporter/my.cnf"
      - "{{ role_path }}/templates/my.cnf.j2"
    dest: "{{ node_config_directory }}/prometheus-mysqld-exporter/my.cnf"
  register: prometheus_conf_mycnf
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart prometheus-mysqld-exporter container

- name: Copying cloud config file for openstack exporter
  vars:
    service: "{{ prometheus_services['prometheus-openstack-exporter'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/prometheus-openstack-exporter/clouds.yml"
  register: prometheus_openstack_exporter_confs
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - "{{ node_custom_config }}/prometheus-openstack-exporter/{{ inventory_hostname }}/clouds.yml"
    - "{{ node_custom_config }}/prometheus-openstack-exporter/clouds.yml"
    - "{{ role_path }}/templates/clouds.yml.j2"
  notify:
    - Restart prometheus-openstack-exporter container

- name: Copying over built in mtail progs
  vars:
    service: "{{ prometheus_services['prometheus-mtail'] }}"
  template:
    src: "{{ role_path }}/templates/mtail_progs/{{ item }}.mtail.j2"
    dest: "{{ node_config_directory }}/prometheus-mtail/{{ item }}.mtail"
    mode: "0660"
  become: true
  register: prometheus_mtail_progs
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_items:
    - "syslog"
  notify:
    - Restart prometheus-mtail container

- name: Find custom mtail progs
  vars:
    service: "{{ prometheus_services['prometheus-mtail'] }}"
  local_action:
    module: find
    path: "{{ node_custom_config }}/mtail"
    pattern: "*.mtail"
  run_once: True
  register: find_custom_mtail_progs
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool

- name: Copying over custom mtail progs
  vars:
    service: "{{ prometheus_services['prometheus-mtail'] }}"
  template:
    src: "{{ item.path }}"
    dest: "{{ node_config_directory }}/prometheus-mtail/{{ item.path | basename }}"
    mode: "0660"
  become: true
  register: prometheus_mtail_custom_progs
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_items: "{{ find_custom_mtail_progs.files }}"
  notify:
    - Restart prometheus-mtail container

- name: Copying over prometheus jiralert config file
  vars:
    service: "{{ prometheus_services['prometheus-jiralert']}}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/prometheus-jiralert/jiralert.yml"
  become: true
  register: prometheus_jiralert_confs
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - "{{ node_custom_config }}/prometheus/{{ inventory_hostname }}/prometheus-jiralert.yml"
    - "{{ node_custom_config }}/prometheus/prometheus-jiralert.yml"
    - "{{ role_path }}/templates/prometheus-jiralert.yml.j2"
  notify:
    - Restart prometheus-jiralert container

- name: Copying over prometheus jiralert template file
  vars:
    service: "{{ prometheus_services['prometheus-jiralert']}}"
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/prometheus-jiralert/jiralert.tmpl"
  become: true
  register: prometheus_jiralert_template
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - "{{ node_custom_config }}/prometheus/{{ inventory_hostname }}/prometheus-jiralert.tmpl"
    - "{{ node_custom_config }}/prometheus/prometheus-jiralert.tmpl"
    - "{{ role_path }}/templates/prometheus-jiralert.tmpl"
  notify:
    - Restart prometheus-jiralert container

- name: Check prometheus containers
  become: true
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    dimensions: "{{ item.value.dimensions }}"
  register: check_prometheus_containers
  when:
    - kolla_action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ prometheus_services }}"
  notify:
    - Restart {{ item.key }} container
