---
- name: Wait for kibana port
  wait_for:
    host: "{{ kolla_internal_vip_address }}"
    port: "{{ kibana_server_port }}"
  run_once: true

- name: Check if kibana index is registered in elasticsearch
  uri:
    url: "{{ internal_protocol }}://{{ kolla_internal_vip_address }}:{{ elasticsearch_port }}/.kibana"
    method: GET
    status_code: 200, 404
  register: query_index_result
  run_once: true

- name: Determine whether Kibana index needs to be created
  set_fact:
    create_kibana_index: >-
      {{ query_index_result.status == 404 and
         query_index_result.get('json', {}).get('error', {}).get('type') == 'index_not_found_exception' }}

- name: Register the kibana index in elasticsearch
  uri:
    url: "{{ internal_protocol }}://{{ kolla_internal_vip_address }}:{{ elasticsearch_port }}/.kibana"
    method: PUT
    body: "{{ kibana_default_index_options | to_json }}"
    body_format: json
    status_code: 200, 201
  register: result
  run_once: true
  when: create_kibana_index | bool

- name: Wait for kibana to register in elasticsearch
  uri:
    url: "{{ internal_protocol }}://{{ kolla_internal_vip_address }}:{{ elasticsearch_port }}/.kibana"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 20
  delay: 2
  run_once: true
  when: create_kibana_index | bool

- name: Change kibana config to set index as defaultIndex
  uri:
    url: "{{ internal_protocol }}://{{ kolla_internal_vip_address }}:{{ elasticsearch_port }}/.kibana/config/*"
    method: PUT
    body:
      defaultIndex: "{{ kibana_default_index_pattern }}"
    body_format: json
    status_code: 200, 201
  run_once: true
  when: false # FIXME FOR ES 6

- name: Get kibana default indexes
  uri:
    HEADER_Content-Type: application/json
    url: "{{ internal_protocol }}://{{ kolla_internal_vip_address }}:{{ elasticsearch_port }}/.kibana"
    method: GET
  register: kibana_default_indexes
  run_once: true
  when: kibana_default_index is defined

- name: Set kibana default indexes fact
  set_fact:
    kibana_default_indexes: "{{ kibana_default_indexes.json | default([]) }}"
  when:
    - kibana_default_indexes is defined
  run_once: true
  connection: local
  when: false # FIXME FOR ES 6

- name: Add index pattern to kibana
  uri:
    url: "{{ internal_protocol }}://{{ kolla_internal_vip_address }}:{{ elasticsearch_port }}/.kibana/index-pattern/{{ kibana_default_index_pattern }}"
    method: PUT
    body: "{{ kibana_default_index | to_json }}"
    body_format: json
    status_code: 201
  run_once: true
  when: false # FIXME FOR ES 6
#    - kibana_default_index is defined
#    - kibana_default_indexes is defined
#    - kibana_default_indexes['.kibana']['mappings']['config']['properties']['defaultIndex'] is not defined
